name: Danger CI

on: ['pull_request']

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Locate Yarn Cache Directory
        id: locate-yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Retrieve Yarn Cache
        id: retrieve-yarn-cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.locate-yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install

      - name: Danger
        run: yarn danger ci
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
